#ifndef BASE_H_
#define BASE_H_

#define PERIPHERAL_BASE 			(0x40000000)

#define AHB_PERIPHERAL_OFFSET		(0x00020000)
#define	AHB_PERIPHERAL				(PERIPHERAL_BASE + AHB_PERIPHERAL_OFFSET)

#define GPIOB_PERIPHERAL_OFFSET		(0x00000400)
#define GPIOB_PERIPHERAL			(AHB_PERIPHERAL + GPIOB_PERIPHERAL_OFFSET)

#define GPIOC_PERIPHERAL_OFFSET		(0x00000800)
#define GPIOC_PERIPHERAL			(AHB_PERIPHERAL + GPIOC_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET 		(0x00003800)
#define RCC_PERIPHERAL				(AHB_PERIPHERAL + RCC_PERIPHERAL_OFFSET)


#endif
